<?php

namespace Laravolt\Suitable\Columns;

class Text extends Column implements ColumnInterface
{
    public function cell($cell, $collection, $loop)
    {
        return $cell->{$this->field};
    }

    static public function make($field, $header = null, $columnAttr = null)
    {
        $column = parent::make($field, $header); // TODO: Change the autogenerated stub

        $column->sortable($columnAttr['sortable'] ?? '');
        $column->searchable($columnAttr['searchable'] ?? '');
        $column->cellAttributes($columnAttr['cellAttributes'] ?? '');

        return $column;
    }
}
