name: Laravolt Platform

on:
  push:
    branches: [ "master" ]

jobs:
  laravolt-platform-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v3
    - name: Install Laravel
      run: composer create-project laravel/laravel -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Copy .env
      run: |
        cd laravel
        php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: |
        cd laravel
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: |
        cd laravel
        php artisan key:generate
    - name: Directory Permissions
      run: |
        cd laravel
        chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        cd laravel
        mkdir -p database
        touch database/database.sqlite
    - name: Install package
      run: cd laravel && composer config repositories.laravolt path ./.. && composer require laravolt/laravolt:dev-master && composer require brianium/paratest --dev && php artisan laravolt:install
    - name: Install package js
      run: |
        cd laravel
        npm install tailwindcss && npm run build
    - name: Migrate database
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        cd laravel
        php artisan migrate
    - name: Pint test
      run: cd laravel && ./vendor/bin/pint --test
    - name: Laravel test
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ':memory:'
      run: cd laravel && php artisan test -p
