name: PHPStan Static Analysis

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpstan.neon'
      - '.github/workflows/phpstan.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.php'
      - 'composer.json'
      - 'composer.lock'
      - 'phpstan.neon'
      - '.github/workflows/phpstan.yml'

jobs:
  phpstan:
    name: PHPStan Analysis
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['8.2', '8.3']
        dependency-version: [prefer-stable]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: bcmath, ctype, curl, gd, json, mbstring, openssl, pdo, xml
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run PHPStan
        run: composer phpstan

      - name: Upload PHPStan results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: phpstan-results-php${{ matrix.php-version }}
          path: |
            phpstan-error-baseline.neon
            .phpstan-cache/
          retention-days: 7

  phpstan-pro:
    name: PHPStan Pro Analysis
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: bcmath, ctype, curl, gd, json, mbstring, openssl, pdo, xml
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Run PHPStan Pro
        run: composer phpstan:pro
        env:
          PHPSTAN_PRO_WEB_PORT: 11111
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security-check:
    name: Security Vulnerability Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Security check
        uses: symfonycorp/security-checker-action@v5